name:                oalg-main
version:             1.0.1.0
github:              "zErichGut/oalg-main"
license:             BSD3
author:              "Erich.Gut"
maintainer:          "zerich.gut@gmail.com"
copyright:           "Erich Gut"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Homology Groups for some Complexes.
category:            Algebra, Simplical Homology, Category Theory

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Simplical homology over simplices as finite list of vertices. Please also see the README on GitHub at <https://github.com/zErichGut/oalg-main#readme>

dependencies:
- base >= 4.7 && < 5
- deepseq >=1.4.4.0
- random >=1.2.0
- array >=0.5.4.0
- time >=1.9.3
- oalg-base >=0.9
- oalg-abg >=0.9
- oalg-top >= 0.2

ghc-options:
- -Wall
- -Wcompat
- -Wno-identities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unticked-promoted-constructors
- -Wno-name-shadowing
- -Wno-unused-top-binds

library:
  source-dirs: src

executables:
  oalg-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oalg-main

tests:
  oalg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oalg-main
