name:                oalg-mtx
version:             3.2.2.0
github:              "zErichGut/oalg-mtx"
license:             BSD-3-Clause
author:              "Erich.Gut"
maintainer:          "zerich.gut@gmail.com"
copyright:           "(c) Erich Gut"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:          Matrix over oriented algebraic structures.
category:          Mathematics, Linear Algebra


# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Matrices over oriented algebraic structures
  
  Please see the README on GitHub at <https://github.com/zErichGut/oalg-mtx#readme>

dependencies:
- base >= 4.7 && < 5
- oalg-pre >= 3.2 && < 4
- oalg-stc >= 3.2 && < 4
- oalg-hom >= 3.2 && < 4
- oalg-sqc >= 3.2 && < 4
- oalg-fin >= 3.2 && < 4
- oalg-lim >= 3.2 && < 4

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unticked-promoted-constructors
- -Wno-name-shadowing
- -Wno-unused-top-binds
- -Wno-incomplete-uni-patterns
# - -Wno-incomplete-patterns
- -Wno-identities

library:
  source-dirs: src

# executables:
#   oalg-mtx-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - oalg-mtx

tests:
  oalg-mtx-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oalg-mtx
