name:                oalg-abg
version:             1.0.0.0
github:              "zErichGut/oalg-abg"
license:             BSD3
author:              "Erich.Gut"
maintainer:          "zerich.gut@gmail.com"
copyright:           "Erich Gut"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Finitely generated abelian groups.
category:            Mathematics, Algebra, Category

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zErichGut/oalg-abg#readme>

dependencies:
- base >= 4.16 && < 5
- oalg-base >= 1.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-name-shadowing
- -Wno-unused-top-binds
- -Wno-incomplete-uni-patterns
- -Wno-unticked-promoted-constructors

library:
  source-dirs: src

# executables:
#   oalg-abg-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - oalg-abg

tests:
  oalg-abg-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oalg-abg
