name:                oalg-pre
version:             1.1.0.0
github:              "zErichGut/oalg-pre"
license:             BSD-3-Clause
author:              "Erich.Gut"
maintainer:          "zerich.gut@gmail.com"
copyright:           "(c) Erich Gut"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Prelude for OAlg.
category:            Mathematics, Algebra, Category

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Basic definitions for algebraic structures on oriented entities.

  Please see the README on GitHub at <https://github.com/zErichGut/oalg-pre#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5 && < 1
- time >= 1.12 && < 2
- deepseq >= 1.4 && < 2
- random >= 1.2 && < 2


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unticked-promoted-constructors
- -Wno-name-shadowing
- -Wno-unused-top-binds
- -Wno-incomplete-uni-patterns
# - -Wno-incomplete-patterns
- -Wno-identities

library:
  source-dirs: src

# executables:
#   oalg-pre-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - oalg-pre

tests:
  oalg-pre-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oalg-pre
