name:                oalg-lim
version:             3.4.1
github:              "zErichGut/oalg-lim"
license:             BSD-3-Clause
author:              "Erich.Gut"
maintainer:          "zerich.gut@gmail.com"
copyright:           "(c) Erich Gut"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:          Limits for oriented algebraic structures.
category:          Mathematics, Algebra, Category

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Limits - in context of categories - serve as a backbone for solving algebraic
  problems, e. g. finding all solutions of the equation @a * x == 0@ is given by the
  kernel of @a@.  

  Please see the README on GitHub at <https://github.com/zErichGut/oalg-lim#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5 && < 1
- oalg-pre >= 3.2 && < 4
- oalg-stc >= 3.2 && < 4
- oalg-hom >= 3.2 && < 4
- oalg-fin >= 3.2 && < 4

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wredundant-constraints
- -Wno-unticked-promoted-constructors
- -Wno-name-shadowing
- -Wno-unused-top-binds
- -Wno-incomplete-uni-patterns
# - -Wno-incomplete-patterns
- -Wno-identities

library:
  source-dirs: src

# executables:
#   oalg-lim-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - oalg-lim

tests:
  oalg-lim-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oalg-lim
