name:                oalg-base
version:             1.1.4.0
github:              "zErichGut/oalg-main/oalg-base"
license:             BSD3
author:              "Erich.Gut"
maintainer:          "zerich.gut@gmail.com"
copyright:           "Erich Gut"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Algebraic structures on oriented entities and limits as a tool kit to solve
                     algebraic problems.
category:            Mathematics, Algebra, Category

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Basic definition of algebraic structures on oriented entities.


  Please see also the README on GitHub at <https://github.com/zErichGut/oalg-main/blob/main/oalg-base/README.md>


dependencies:
- base >= 4.17 && < 5
- deepseq >= 1.4 && < 2
- random >= 1.2 && < 2
- array >= 0.5 && < 1
- time >= 1.12 && < 2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unticked-promoted-constructors
- -Wno-name-shadowing
- -Wno-unused-top-binds
- -Wno-incomplete-uni-patterns
# - -Wno-incomplete-patterns
- -Wno-identities


library:
  source-dirs: src

# executables:
#   oalg-base-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - oalg-base

tests:
  oalg-base-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oalg-base
